### ISSUE TITLE
Parse function out of the test.txt

### ISSUE THREAD

**Issue by ryanmklee** [ryanmklee/elisa_fanclub_part2#3]
In the profiler's code, we need to extract the function name not all the other details so our graph doesn't have a large overflow.

For example, using the profiler the function name is

`{method 'query' of 'sklearn.neighbors.kd_tree.BinaryTree' objects}`

we want instead to be able to clean this data 

to return 

`'sklearn.neighbors.kd_tree.BinaryTree' `

**Comment by Gao-Gary** [comment]
implemented w/ 292c56561d595818819d850dacf09bf1fb8470b9
