### ISSUE TITLE
Abstract data filtering from barchart outside the scope of the class

### ISSUE THREAD

**Issue by ryanmklee** [ryanmklee/elisa_fanclub_part2#5]
Bar chart data filtering is done inside it's class, we should probably move it outside of the class to abstract it for other graphs and extract different data, then pass in the relevant data to each graph we will have. We will need to move the function `_filter_data` out from the BarGraph class and into the main function or somewhere else.

**Comment by Gao-Gary** [comment]
1945c0ff58a0e4800b7d37ed387378096eb6d218 introduces VizFactory that moves pre-processing logic outside of builder classes
